'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { translations as extendedTranslations } from '../i18n/translations'

export type Language = 'pt-BR' | 'en-US' | 'es-ES'

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionaries - merge base translations with extended ones
const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Bem-vindo ao painel administrativo do SwiftEDU',
    'dashboard.totalStudents': 'Total de Alunos',
    'dashboard.activeCourses': 'Cursos Ativos',
    'dashboard.completionRate': 'Taxa de Conclusão',
    'dashboard.enrollments': 'Matrículas',
    'dashboard.recentActivities': 'Atividades Recentes',
    'dashboard.popularCourses': 'Cursos Mais Populares',
    'dashboard.basedOnEnrollments': 'Baseado no número de matrículas',
    'dashboard.instructors': 'Instrutores',
    'dashboard.draftCourses': 'Cursos em Rascunho',
    'dashboard.ongoingEnrollments': 'Matrículas em Andamento',
    'dashboard.noRecentActivity': 'Nenhuma atividade recente',
    'dashboard.noCoursesYet': 'Nenhum curso com matrículas ainda',
    'dashboard.students': 'alunos',
    'dashboard.active': 'ativos',
    'dashboard.total': 'total',
    'dashboard.completed': 'concluídos',
    'dashboard.totalEnrollments': 'Total de matrículas',
    'dashboard.startedCourse': 'iniciou o curso',
    'dashboard.completedCourse': 'concluiu o curso',
    'dashboard.minutesAgo': 'min atrás',
    'dashboard.hoursAgo': 'horas atrás',
    'dashboard.daysAgo': 'dias atrás',
    'dashboard.userJoined': 'entrou na plataforma',
    'dashboard.createdCourse': 'criou o curso',
    'dashboard.publishedCourse': 'publicou o curso',
    'dashboard.enrolledInCourse': 'se matriculou em',
    'dashboard.newStudentEnrolled': 'recebeu nova matrícula de',
    'dashboard.viewAll': 'Ver todos',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.subtitle': 'Gerencie suas preferências e informações pessoais',
    'settings.profile': 'Perfil',
    'settings.password': 'Senha',
    'settings.notifications': 'Notificações',
    'settings.appearance': 'Aparência',
    'settings.privacy': 'Privacidade',
    'settings.profileInfo': 'Informações do Perfil',
    'settings.fullName': 'Nome Completo',
    'settings.email': 'Email',
    'settings.phone': 'Telefone',
    'settings.bio': 'Biografia',
    'settings.emailCannotChange': 'Email não pode ser alterado',
    'settings.bioPlaceholder': 'Conte um pouco sobre você...',
    'settings.saveChanges': 'Salvar Alterações',
    'settings.saving': 'Salvando...',
    'settings.changePassword': 'Alterar Senha',
    'settings.currentPassword': 'Senha Atual',
    'settings.newPassword': 'Nova Senha',
    'settings.confirmPassword': 'Confirmar Nova Senha',
    'settings.minCharacters': 'Mínimo 6 caracteres',
    'settings.changing': 'Alterando...',
    'settings.notificationPreferences': 'Preferências de Notificação',
    'settings.emailNotifications': 'Notificações por Email',
    'settings.emailNotificationsDesc': 'Receber notificações importantes por email',
    'settings.courseUpdates': 'Atualizações de Cursos',
    'settings.courseUpdatesDesc': 'Notificar sobre mudanças nos cursos matriculados',
    'settings.newEnrollments': 'Novas Matrículas',
    'settings.newEnrollmentsDesc': 'Notificar quando alunos se matriculam em seus cursos',
    'settings.systemUpdates': 'Atualizações do Sistema',
    'settings.systemUpdatesDesc': 'Notificar sobre manutenções e novidades',
    'settings.savePreferences': 'Salvar Preferências',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Escuro',
    'settings.auto': 'Automático',
    'settings.language': 'Idioma',
    'settings.dateFormat': 'Formato de Data',
    'settings.saveAppearance': 'Salvar Aparência',
    'settings.profileVisibility': 'Visibilidade do Perfil',
    'settings.public': 'Público - Todos podem ver',
    'settings.connections': 'Conexões - Apenas contatos',
    'settings.private': 'Privado - Apenas você',
    'settings.showEmail': 'Mostrar Email no Perfil',
    'settings.showEmailDesc': 'Permitir que outros vejam seu email',
    'settings.showPhone': 'Mostrar Telefone no Perfil',
    'settings.showPhoneDesc': 'Permitir que outros vejam seu telefone',
    'settings.savePrivacy': 'Salvar Privacidade',
    'settings.systemInfo': 'Informações do Sistema',
    'settings.version': 'Versão',
    'settings.database': 'Banco de Dados',
    'settings.lastUpdate': 'Última Atualização',
    'settings.success': 'salvas com sucesso!',
    'settings.error': 'Erro ao salvar',
    'settings.profileUpdated': 'Perfil atualizado com sucesso!',
    'settings.passwordChanged': 'Senha alterada com sucesso!',
    'settings.passwordsDontMatch': 'As senhas não coincidem',
    'settings.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
    'settings.administrator': 'Administrador',
    'settings.instructor': 'Instrutor',
    'settings.student': 'Aluno',
    'settings.noName': 'Sem nome',
    
    // Navigation
    'nav.dashboard': 'Visão Geral',
    'nav.courses': 'Cursos',
    'nav.users': 'Usuários',
    'nav.reports': 'Relatórios',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    'nav.loggingOut': 'Saindo...',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.close': 'Fechar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.download': 'Baixar',
    'common.upload': 'Enviar',
    'common.refresh': 'Atualizar',
    'common.reset': 'Resetar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.all': 'Todos',
    'common.none': 'Nenhum',
    'common.select': 'Selecionar',
    'common.selected': 'Selecionado',
    'common.actions': 'Ações',
    'common.status': 'Status',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.pending': 'Pendente',
    'common.completed': 'Concluído',
    'common.failed': 'Falhou',
    'common.new': 'Novo',
    'common.add': 'Adicionar',
    'common.remove': 'Remover',
    'common.update': 'Atualizar',
    'common.create': 'Criar',
    'common.view': 'Visualizar',
    'common.details': 'Detalhes',
    'common.settings': 'Configurações',
    'common.help': 'Ajuda',
    'common.about': 'Sobre',
    'common.contact': 'Contato',
    'common.privacy': 'Privacidade',
    'common.terms': 'Termos',
    'common.logout': 'Sair',
    'common.login': 'Entrar',
    'common.register': 'Registrar',
    'common.forgotPassword': 'Esqueceu a senha?',
    'common.resetPassword': 'Resetar Senha',
    'common.changePassword': 'Alterar Senha',
    'common.profile': 'Perfil',
    'common.account': 'Conta',
    'common.preferences': 'Preferências',
    'common.notifications': 'Notificações',
    'common.messages': 'Mensagens',
    'common.alerts': 'Alertas',
    'common.reports': 'Relatórios',
    'common.analytics': 'Análises',
    'common.statistics': 'Estatísticas',
    'common.dashboard': 'Painel',
    'common.home': 'Início',
    'common.welcome': 'Bem-vindo',
    'common.goodbye': 'Até logo',
    
    // Users page
    'users.title': 'Usuários',
    'users.subtitle': 'Gerencie os usuários da plataforma',
    'users.newUser': 'Novo Usuário',
    'users.searchPlaceholder': 'Buscar por nome ou email...',
    'users.filters': 'Filtros',
    'users.name': 'Usuário',
    'users.contact': 'Contato',
    'users.role': 'Função',
    'users.status': 'Status',
    'users.createdAt': 'Criado em',
    'users.actions': 'Ações',
    'users.noName': 'Sem nome',
    'users.active': 'Ativo',
    'users.frozen': 'Congelado',
    'users.freeze': 'Congelar',
    'users.unfreeze': 'Descongelar',
    'users.edit': 'Editar',
    'users.delete': 'Excluir',
    'users.resetPassword': 'Resetar Senha',
    'users.administrator': 'Administrador',
    'users.instructor': 'Instrutor',
    'users.student': 'Aluno',
    'users.createUser': 'Criar Novo Usuário',
    'users.editUser': 'Editar Usuário',
    'users.deleteUser': 'Excluir Usuário',
    'users.fullName': 'Nome Completo',
    'users.email': 'Email',
    'users.phone': 'Telefone',
    'users.password': 'Senha',
    'users.confirmPassword': 'Confirmar Senha',
    'users.selectRole': 'Selecione uma função',
    'users.creating': 'Criando...',
    'users.updating': 'Atualizando...',
    'users.deleting': 'Excluindo...',
    'users.confirmDelete': 'Tem certeza que deseja excluir este usuário?',
    'users.confirmFreeze': 'Tem certeza que deseja congelar este usuário?',
    'users.confirmUnfreeze': 'Tem certeza que deseja descongelar este usuário?',
    'users.userCreated': 'Usuário criado com sucesso!',
    'users.userUpdated': 'Usuário atualizado com sucesso!',
    'users.userDeleted': 'Usuário excluído com sucesso!',
    'users.userFrozen': 'Usuário congelado com sucesso!',
    'users.userUnfrozen': 'Usuário descongelado com sucesso!',
    'users.passwordReset': 'Senha resetada com sucesso!',
    'users.newPassword': 'Nova senha',
    'users.error': 'Erro ao processar requisição',
    
    // Courses page
    'courses.title': 'Cursos',
    'courses.subtitle': 'Gerencie os cursos da plataforma',
    'courses.newCourse': 'Novo Curso',
    'courses.searchPlaceholder': 'Buscar cursos...',
    'courses.allCategories': 'Todas as Categorias',
    'courses.filters': 'Filtros',
    'courses.courseTitle': 'Curso',
    'courses.instructor': 'Instrutor',
    'courses.students': 'Alunos',
    'courses.status': 'Status',
    'courses.actions': 'Ações',
    'courses.edit': 'Editar',
    'courses.delete': 'Excluir',
    'courses.view': 'Visualizar',
    'courses.publish': 'Publicar',
    'courses.unpublish': 'Despublicar',
    'courses.published': 'Publicado',
    'courses.draft': 'Rascunho',
    'courses.category': 'Categoria',
    'courses.duration': 'Duração',
    'courses.level': 'Nível',
    'courses.price': 'Preço',
    'courses.free': 'Gratuito',
    'courses.description': 'Descrição',
    'courses.modules': 'Módulos',
    'courses.enrolled': 'matriculados',
    'courses.noInstructor': 'Sem instrutor',
    'courses.beginner': 'Iniciante',
    'courses.intermediate': 'Intermediário',
    'courses.advanced': 'Avançado',
    'courses.engineering': 'Engenharia',
    'courses.safety': 'Segurança',
    'courses.operations': 'Operações',
    'courses.maintenance': 'Manutenção',
    'courses.loading': 'Carregando cursos...',
    'courses.noCourses': 'Nenhum curso encontrado',
    
    // Reports page
    'reports.title': 'Relatórios',
    'reports.subtitle': 'Gere e exporte relatórios detalhados',
    'reports.selectType': 'Selecione o tipo de relatório',
    'reports.dateRange': 'Período',
    'reports.from': 'De',
    'reports.to': 'Até',
    'reports.format': 'Formato',
    'reports.generateReport': 'Gerar Relatório',
    'reports.generating': 'Gerando...',
    'reports.download': 'Baixar',
    'reports.preview': 'Visualizar',
    'reports.enrollmentReport': 'Relatório de Matrículas',
    'reports.enrollmentReportDesc': 'Detalhes de todas as matrículas no período',
    'reports.completionReport': 'Relatório de Conclusões',
    'reports.completionReportDesc': 'Cursos concluídos e taxas de conclusão',
    'reports.userActivityReport': 'Relatório de Atividade de Usuários',
    'reports.userActivityReportDesc': 'Atividades e engajamento dos usuários',
    'reports.financialReport': 'Relatório Financeiro',
    'reports.financialReportDesc': 'Receitas e análise financeira',
    'reports.studentName': 'Nome do Aluno',
    'reports.courseName': 'Nome do Curso',
    'reports.enrollmentDate': 'Data de Matrícula',
    'reports.completionDate': 'Data de Conclusão',
    'reports.progress': 'Progresso',
    'reports.lastActivity': 'Última Atividade',
    'reports.totalRevenue': 'Receita Total',
    'reports.averageCompletion': 'Taxa Média de Conclusão',
    'reports.reportGenerated': 'Relatório gerado com sucesso!',
    'reports.reportError': 'Erro ao gerar relatório',
    'reports.noData': 'Sem dados para o período selecionado',
    'reports.export': 'Exportar',
    'reports.exportCSV': 'Exportar CSV',
    'reports.exportPDF': 'Exportar PDF',
    'reports.print': 'Imprimir',
    
    // Login page
    'login.title': 'Bem-vindo ao SwiftEDU',
    'login.subtitle': 'Sistema de Gestão de Aprendizagem de Engenharia Naval e Offshore',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.signIn': 'Entrar',
    'login.signing': 'Entrando...',
    'login.noAccount': 'Não tem uma conta?',
    'login.contactAdmin': 'Contate o administrador',
    'login.invalidCredentials': 'Email ou senha inválidos',
    'login.error': 'Erro ao fazer login',
    'login.systemTitle': 'SwiftEDU',
    'login.systemSubtitle': 'Sistema de Gestão de Aprendizagem',
    'login.emailPlaceholder': 'Digite seu email',
    'login.emailAriaLabel': 'Campo de email',
    'login.passwordPlaceholder': 'Digite sua senha',
    'login.passwordAriaLabel': 'Campo de senha',
    'login.showPassword': 'Mostrar senha',
    'login.hidePassword': 'Ocultar senha',
    'login.rememberAriaLabel': 'Lembrar de mim',
    'login.enter': 'Entrar',
    'login.loginAriaLabel': 'Fazer login',
    'login.secureConnection': 'Conexão segura e criptografada',
    'login.loginError': 'Erro ao fazer login',
    'login.unexpectedError': 'Erro inesperado',
    'login.confirmEmail': 'Por favor, confirme seu email',
    'login.rememberMe': 'Lembrar-me',
    'login.forgotPassword': 'Esqueci a minha senha',
    'login.viewCourses': 'Ver Cursos Disponíveis',
    'login.contactPrompt': 'Interessado em algum curso?',
    'login.contactButton': 'Fale Conosco',
    'login.tooManyAttempts': 'Muitas tentativas de login. Por favor, aguarde alguns minutos.',
    'login.blockedRequest': 'Requisição bloqueada por segurança. Tente novamente.',
    
    // Forgot Password
    'forgotPassword.title': 'Recuperar Senha',
    'forgotPassword.subtitle': 'Digite seu email para receber instruções',
    'forgotPassword.instructions': 'Digite seu email cadastrado e enviaremos instruções para redefinir sua senha.',
    'forgotPassword.email': 'Email',
    'forgotPassword.emailPlaceholder': 'Digite seu email',
    'forgotPassword.send': 'Enviar Instruções',
    'forgotPassword.cancel': 'Cancelar',
    'forgotPassword.close': 'Fechar',
    'forgotPassword.emailRequired': 'Email é obrigatório',
    'forgotPassword.emailInvalid': 'Email inválido',
    'forgotPassword.emailNotFound': 'Este email não está cadastrado no sistema',
    'forgotPassword.sendError': 'Erro ao enviar email. Tente novamente.',
    'forgotPassword.unexpectedError': 'Erro inesperado. Tente novamente.',
    'forgotPassword.successTitle': 'Email Enviado!',
    'forgotPassword.successMessage': 'Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.',
    
    // Reset Password
    'resetPassword.title': 'Redefinir Senha',
    'resetPassword.subtitle': 'Digite sua nova senha',
    'resetPassword.expiredTitle': 'Link Expirado',
    'resetPassword.expiredSubtitle': 'O link de recuperação não é mais válido',
    'resetPassword.newPassword': 'Nova Senha',
    'resetPassword.confirmPassword': 'Confirmar Nova Senha',
    'resetPassword.passwordPlaceholder': 'Digite sua nova senha',
    'resetPassword.confirmPasswordPlaceholder': 'Confirme sua nova senha',
    'resetPassword.passwordRequirement': 'Mínimo 6 caracteres',
    'resetPassword.updatePassword': 'Atualizar Senha',
    'resetPassword.backToLogin': 'Voltar ao Login',
    'resetPassword.passwordRequired': 'Nova senha é obrigatória',
    'resetPassword.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
    'resetPassword.passwordMismatch': 'As senhas não coincidem',
    'resetPassword.linkExpired': 'O link de recuperação expirou',
    'resetPassword.linkInvalid': 'Link de recuperação inválido',
    'resetPassword.sessionExpired': 'Sessão expirada. Solicite um novo link de recuperação.',
    'resetPassword.sessionError': 'Erro na sessão de recuperação. Solicite um novo link.',
    'resetPassword.updateError': 'Erro ao atualizar senha. Tente novamente.',
    'resetPassword.unexpectedError': 'Erro inesperado. Tente novamente.',
    'resetPassword.successTitle': 'Senha Atualizada!',
    'resetPassword.successMessage': 'Sua senha foi alterada com sucesso. Você será redirecionado para o login.',
    'resetPassword.linkExpiredTitle': 'Link Expirado',
    'resetPassword.linkExpiredMessage': 'O link de recuperação de senha expirou. Por favor, solicite um novo link.',
    'resetPassword.requestNewLink': 'Solicitar Novo Link',
    
    // Contact form
    'contact.title': 'Fale Conosco',
    'contact.subtitle': 'Entre em contato conosco sobre cursos e oportunidades',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Digite seu nome completo',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Digite seu email',
    'contact.courseInterest': 'Interesse em Curso',
    'contact.courseInterestPlaceholder': 'Qual curso te interessa? (opcional)',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Digite sua mensagem ou dúvida...',
    'contact.send': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'contact.success': 'Seu cliente de email foi aberto com a mensagem pronta. Complete o envio no seu email!',
    'contact.error': 'Erro ao enviar mensagem. Tente novamente.',
    'contact.cancel': 'Cancelar',
    'contact.close': 'Fechar',
    
    // Form validations
    'validation.required': 'Este campo é obrigatório',
    'validation.email': 'Email inválido',
    'validation.minLength': 'Mínimo de {min} caracteres',
    'validation.maxLength': 'Máximo de {max} caracteres',
    'validation.passwordMatch': 'As senhas não coincidem',
    'validation.phoneInvalid': 'Telefone inválido',
    
    // Buttons
    'button.save': 'Salvar',
    'button.cancel': 'Cancelar',
    'button.delete': 'Excluir',
    'button.edit': 'Editar',
    'button.create': 'Criar',
    'button.update': 'Atualizar',
    'button.close': 'Fechar',
    'button.confirm': 'Confirmar',
    'button.back': 'Voltar',
    'button.next': 'Próximo',
    'button.previous': 'Anterior',
    'button.finish': 'Finalizar',
    'button.search': 'Buscar',
    'button.filter': 'Filtrar',
    'button.export': 'Exportar',
    'button.import': 'Importar',
    'button.refresh': 'Atualizar',
    'button.view': 'Visualizar',
    'button.download': 'Baixar',
    'button.upload': 'Enviar',
    'button.select': 'Selecionar',
    'button.clear': 'Limpar',
    'button.reset': 'Resetar',
    'button.apply': 'Aplicar',
    'button.submit': 'Enviar',
    'button.continue': 'Continuar',
    'button.skip': 'Pular',
    'button.retry': 'Tentar Novamente',
    'button.loading': 'Carregando...',
  },
  'en-US': {
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Welcome to SwiftEDU administrative panel',
    'dashboard.totalStudents': 'Total Students',
    'dashboard.activeCourses': 'Active Courses',
    'dashboard.completionRate': 'Completion Rate',
    'dashboard.enrollments': 'Enrollments',
    'dashboard.recentActivities': 'Recent Activities',
    'dashboard.popularCourses': 'Most Popular Courses',
    'dashboard.basedOnEnrollments': 'Based on enrollment numbers',
    'dashboard.instructors': 'Instructors',
    'dashboard.draftCourses': 'Draft Courses',
    'dashboard.ongoingEnrollments': 'Ongoing Enrollments',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.noCoursesYet': 'No courses with enrollments yet',
    'dashboard.students': 'students',
    'dashboard.active': 'active',
    'dashboard.total': 'total',
    'dashboard.completed': 'completed',
    'dashboard.totalEnrollments': 'Total enrollments',
    'dashboard.startedCourse': 'started the course',
    'dashboard.completedCourse': 'completed the course',
    'dashboard.minutesAgo': 'min ago',
    'dashboard.hoursAgo': 'hours ago',
    'dashboard.daysAgo': 'days ago',
    'dashboard.userJoined': 'joined the platform',
    'dashboard.createdCourse': 'created the course',
    'dashboard.publishedCourse': 'published the course',
    'dashboard.enrolledInCourse': 'enrolled in',
    'dashboard.newStudentEnrolled': 'received new enrollment from',
    'dashboard.viewAll': 'View all',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your preferences and personal information',
    'settings.profile': 'Profile',
    'settings.password': 'Password',
    'settings.notifications': 'Notifications',
    'settings.appearance': 'Appearance',
    'settings.privacy': 'Privacy',
    'settings.profileInfo': 'Profile Information',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email',
    'settings.phone': 'Phone',
    'settings.bio': 'Biography',
    'settings.emailCannotChange': 'Email cannot be changed',
    'settings.bioPlaceholder': 'Tell us about yourself...',
    'settings.saveChanges': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.minCharacters': 'Minimum 6 characters',
    'settings.changing': 'Changing...',
    'settings.notificationPreferences': 'Notification Preferences',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive important notifications by email',
    'settings.courseUpdates': 'Course Updates',
    'settings.courseUpdatesDesc': 'Notify about changes in enrolled courses',
    'settings.newEnrollments': 'New Enrollments',
    'settings.newEnrollmentsDesc': 'Notify when students enroll in your courses',
    'settings.systemUpdates': 'System Updates',
    'settings.systemUpdatesDesc': 'Notify about maintenance and news',
    'settings.savePreferences': 'Save Preferences',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.auto': 'Automatic',
    'settings.language': 'Language',
    'settings.dateFormat': 'Date Format',
    'settings.saveAppearance': 'Save Appearance',
    'settings.profileVisibility': 'Profile Visibility',
    'settings.public': 'Public - Everyone can see',
    'settings.connections': 'Connections - Only contacts',
    'settings.private': 'Private - Only you',
    'settings.showEmail': 'Show Email in Profile',
    'settings.showEmailDesc': 'Allow others to see your email',
    'settings.showPhone': 'Show Phone in Profile',
    'settings.showPhoneDesc': 'Allow others to see your phone',
    'settings.savePrivacy': 'Save Privacy',
    'settings.systemInfo': 'System Information',
    'settings.version': 'Version',
    'settings.database': 'Database',
    'settings.lastUpdate': 'Last Update',
    'settings.success': 'saved successfully!',
    'settings.error': 'Error saving',
    'settings.profileUpdated': 'Profile updated successfully!',
    'settings.passwordChanged': 'Password changed successfully!',
    'settings.passwordsDontMatch': 'Passwords do not match',
    'settings.passwordTooShort': 'Password must be at least 6 characters',
    'settings.administrator': 'Administrator',
    'settings.instructor': 'Instructor',
    'settings.student': 'Student',
    'settings.noName': 'No name',
    
    // Navigation
    'nav.dashboard': 'Overview',
    'nav.courses': 'Courses',
    'nav.users': 'Users',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.loggingOut': 'Logging out...',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.refresh': 'Refresh',
    'common.reset': 'Reset',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.selected': 'Selected',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.failed': 'Failed',
    'common.new': 'New',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.view': 'View',
    'common.details': 'Details',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.forgotPassword': 'Forgot password?',
    'common.resetPassword': 'Reset Password',
    'common.changePassword': 'Change Password',
    'common.profile': 'Profile',
    'common.account': 'Account',
    'common.preferences': 'Preferences',
    'common.notifications': 'Notifications',
    'common.messages': 'Messages',
    'common.alerts': 'Alerts',
    'common.reports': 'Reports',
    'common.analytics': 'Analytics',
    'common.statistics': 'Statistics',
    'common.dashboard': 'Dashboard',
    'common.home': 'Home',
    'common.welcome': 'Welcome',
    'common.goodbye': 'Goodbye',
    
    // Login page
    'login.systemTitle': 'SwiftEDU',
    'login.systemSubtitle': 'Learning Management System',
    'login.emailPlaceholder': 'Enter your email',
    'login.emailAriaLabel': 'Email field',
    'login.passwordPlaceholder': 'Enter your password',
    'login.passwordAriaLabel': 'Password field',
    'login.showPassword': 'Show password',
    'login.hidePassword': 'Hide password',
    'login.rememberAriaLabel': 'Remember me',
    'login.enter': 'Sign In',
    'login.loginAriaLabel': 'Sign in',
    'login.secureConnection': 'Secure and encrypted connection',
    'login.loginError': 'Login error',
    'login.unexpectedError': 'Unexpected error',
    'login.confirmEmail': 'Please confirm your email',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot my password',
    'login.viewCourses': 'View Available Courses',
    'login.contactPrompt': 'Interested in any course?',
    'login.contactButton': 'Contact Us',
    'login.tooManyAttempts': 'Too many login attempts. Please wait a few minutes.',
    'login.blockedRequest': 'Request blocked for security. Please try again.',

    // Forgot Password
    'forgotPassword.title': 'Reset Password',
    'forgotPassword.subtitle': 'Enter your email to receive instructions',
    'forgotPassword.instructions': 'Enter your registered email and we will send instructions to reset your password.',
    'forgotPassword.email': 'Email',
    'forgotPassword.emailPlaceholder': 'Enter your email',
    'forgotPassword.send': 'Send Instructions',
    'forgotPassword.cancel': 'Cancel',
    'forgotPassword.close': 'Close',
    'forgotPassword.emailRequired': 'Email is required',
    'forgotPassword.emailInvalid': 'Invalid email',
    'forgotPassword.emailNotFound': 'This email is not registered in the system',
    'forgotPassword.sendError': 'Error sending email. Please try again.',
    'forgotPassword.unexpectedError': 'Unexpected error. Please try again.',
    'forgotPassword.successTitle': 'Email Sent!',
    'forgotPassword.successMessage': 'Check your inbox and follow the instructions to reset your password.',
    
    // Reset Password
    'resetPassword.title': 'Reset Password',
    'resetPassword.subtitle': 'Enter your new password',
    'resetPassword.expiredTitle': 'Link Expired',
    'resetPassword.expiredSubtitle': 'The recovery link is no longer valid',
    'resetPassword.newPassword': 'New Password',
    'resetPassword.confirmPassword': 'Confirm New Password',
    'resetPassword.passwordPlaceholder': 'Enter your new password',
    'resetPassword.confirmPasswordPlaceholder': 'Confirm your new password',
    'resetPassword.passwordRequirement': 'Minimum 6 characters',
    'resetPassword.updatePassword': 'Update Password',
    'resetPassword.backToLogin': 'Back to Login',
    'resetPassword.passwordRequired': 'New password is required',
    'resetPassword.passwordTooShort': 'Password must be at least 6 characters',
    'resetPassword.passwordMismatch': 'Passwords do not match',
    'resetPassword.linkExpired': 'The recovery link has expired',
    'resetPassword.linkInvalid': 'Invalid recovery link',
    'resetPassword.sessionExpired': 'Session expired. Please request a new recovery link.',
    'resetPassword.sessionError': 'Error in recovery session. Please request a new link.',
    'resetPassword.updateError': 'Error updating password. Please try again.',
    'resetPassword.unexpectedError': 'Unexpected error. Please try again.',
    'resetPassword.successTitle': 'Password Updated!',
    'resetPassword.successMessage': 'Your password has been successfully changed. You will be redirected to login.',
    'resetPassword.linkExpiredTitle': 'Link Expired',
    'resetPassword.linkExpiredMessage': 'The password recovery link has expired. Please request a new link.',
    'resetPassword.requestNewLink': 'Request New Link',
    
    // Contact form
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch about courses and opportunities',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Enter your full name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Enter your email',
    'contact.courseInterest': 'Course Interest',
    'contact.courseInterestPlaceholder': 'Which course interests you? (optional)',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Enter your message or question...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Your email client was opened with the message ready. Complete sending in your email!',
    'contact.error': 'Error sending message. Please try again.',
    'contact.cancel': 'Cancel',
    'contact.close': 'Close',
  },
  'es-ES': {
    // Dashboard
    'dashboard.title': 'Panel de Control',
    'dashboard.subtitle': 'Bienvenido al panel administrativo de SwiftEDU',
    'dashboard.totalStudents': 'Total de Estudiantes',
    'dashboard.activeCourses': 'Cursos Activos',
    'dashboard.completionRate': 'Tasa de Finalización',
    'dashboard.enrollments': 'Inscripciones',
    'dashboard.recentActivities': 'Actividades Recientes',
    'dashboard.popularCourses': 'Cursos Más Populares',
    'dashboard.basedOnEnrollments': 'Basado en el número de inscripciones',
    'dashboard.instructors': 'Instructores',
    'dashboard.draftCourses': 'Cursos en Borrador',
    'dashboard.ongoingEnrollments': 'Inscripciones en Curso',
    'dashboard.noRecentActivity': 'Sin actividad reciente',
    'dashboard.noCoursesYet': 'Aún no hay cursos con inscripciones',
    'dashboard.students': 'estudiantes',
    'dashboard.active': 'activos',
    'dashboard.total': 'total',
    'dashboard.completed': 'completados',
    'dashboard.totalEnrollments': 'Total de inscripciones',
    'dashboard.startedCourse': 'comenzó el curso',
    'dashboard.completedCourse': 'completó el curso',
    'dashboard.minutesAgo': 'min atrás',
    'dashboard.hoursAgo': 'horas atrás',
    'dashboard.daysAgo': 'días atrás',
    'dashboard.userJoined': 'se unió a la plataforma',
    'dashboard.createdCourse': 'creó el curso',
    'dashboard.publishedCourse': 'publicó el curso',
    'dashboard.enrolledInCourse': 'se inscribió en',
    'dashboard.newStudentEnrolled': 'recibió nueva inscripción de',
    'dashboard.viewAll': 'Ver todos',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Gestiona tus preferencias e información personal',
    'settings.profile': 'Perfil',
    'settings.password': 'Contraseña',
    'settings.notifications': 'Notificaciones',
    'settings.appearance': 'Apariencia',
    'settings.privacy': 'Privacidad',
    'settings.profileInfo': 'Información del Perfil',
    'settings.fullName': 'Nombre Completo',
    'settings.email': 'Correo Electrónico',
    'settings.phone': 'Teléfono',
    'settings.bio': 'Biografía',
    'settings.emailCannotChange': 'El correo no se puede cambiar',
    'settings.bioPlaceholder': 'Cuéntanos sobre ti...',
    'settings.saveChanges': 'Guardar Cambios',
    'settings.saving': 'Guardando...',
    'settings.changePassword': 'Cambiar Contraseña',
    'settings.currentPassword': 'Contraseña Actual',
    'settings.newPassword': 'Nueva Contraseña',
    'settings.confirmPassword': 'Confirmar Nueva Contraseña',
    'settings.minCharacters': 'Mínimo 6 caracteres',
    'settings.changing': 'Cambiando...',
    'settings.notificationPreferences': 'Preferencias de Notificación',
    'settings.emailNotifications': 'Notificaciones por Correo',
    'settings.emailNotificationsDesc': 'Recibir notificaciones importantes por correo',
    'settings.courseUpdates': 'Actualizaciones de Cursos',
    'settings.courseUpdatesDesc': 'Notificar sobre cambios en cursos inscritos',
    'settings.newEnrollments': 'Nuevas Inscripciones',
    'settings.newEnrollmentsDesc': 'Notificar cuando estudiantes se inscriben en tus cursos',
    'settings.systemUpdates': 'Actualizaciones del Sistema',
    'settings.systemUpdatesDesc': 'Notificar sobre mantenimiento y novedades',
    'settings.savePreferences': 'Guardar Preferencias',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Oscuro',
    'settings.auto': 'Automático',
    'settings.language': 'Idioma',
    'settings.dateFormat': 'Formato de Fecha',
    'settings.saveAppearance': 'Guardar Apariencia',
    'settings.profileVisibility': 'Visibilidad del Perfil',
    'settings.public': 'Público - Todos pueden ver',
    'settings.connections': 'Conexiones - Solo contactos',
    'settings.private': 'Privado - Solo tú',
    'settings.showEmail': 'Mostrar Correo en el Perfil',
    'settings.showEmailDesc': 'Permitir que otros vean tu correo',
    'settings.showPhone': 'Mostrar Teléfono en el Perfil',
    'settings.showPhoneDesc': 'Permitir que otros vean tu teléfono',
    'settings.savePrivacy': 'Guardar Privacidad',
    'settings.systemInfo': 'Información del Sistema',
    'settings.version': 'Versión',
    'settings.database': 'Base de Datos',
    'settings.lastUpdate': 'Última Actualización',
    'settings.success': 'guardadas con éxito!',
    'settings.error': 'Error al guardar',
    'settings.profileUpdated': '¡Perfil actualizado con éxito!',
    'settings.passwordChanged': '¡Contraseña cambiada con éxito!',
    'settings.passwordsDontMatch': 'Las contraseñas no coinciden',
    'settings.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'settings.administrator': 'Administrador',
    'settings.instructor': 'Instructor',
    'settings.student': 'Estudiante',
    'settings.noName': 'Sin nombre',
    
    // Navigation
    'nav.dashboard': 'Vista General',
    'nav.courses': 'Cursos',
    'nav.users': 'Usuarios',
    'nav.reports': 'Informes',
    'nav.settings': 'Configuración',
    'nav.logout': 'Salir',
    'nav.loggingOut': 'Saliendo...',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.download': 'Descargar',
    'common.upload': 'Subir',
    'common.refresh': 'Actualizar',
    'common.reset': 'Restablecer',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.select': 'Seleccionar',
    'common.selected': 'Seleccionado',
    'common.actions': 'Acciones',
    'common.status': 'Estado',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.pending': 'Pendiente',
    'common.completed': 'Completado',
    'common.failed': 'Falló',
    'common.new': 'Nuevo',
    'common.add': 'Agregar',
    'common.remove': 'Eliminar',
    'common.update': 'Actualizar',
    'common.create': 'Crear',
    'common.view': 'Ver',
    'common.details': 'Detalles',
    'common.settings': 'Configuración',
    'common.help': 'Ayuda',
    'common.about': 'Acerca de',
    'common.contact': 'Contacto',
    'common.privacy': 'Privacidad',
    'common.terms': 'Términos',
    'common.logout': 'Salir',
    'common.login': 'Iniciar Sesión',
    'common.register': 'Registrarse',
    'common.forgotPassword': '¿Olvidaste tu contraseña?',
    'common.resetPassword': 'Restablecer Contraseña',
    'common.changePassword': 'Cambiar Contraseña',
    'common.profile': 'Perfil',
    'common.account': 'Cuenta',
    'common.preferences': 'Preferencias',
    'common.notifications': 'Notificaciones',
    'common.messages': 'Mensajes',
    'common.alerts': 'Alertas',
    'common.reports': 'Informes',
    'common.analytics': 'Análisis',
    'common.statistics': 'Estadísticas',
    'common.dashboard': 'Panel',
    'common.home': 'Inicio',
    'common.welcome': 'Bienvenido',
    'common.goodbye': 'Adiós',
    
    // Login page
    'login.systemTitle': 'SwiftEDU',
    'login.systemSubtitle': 'Sistema de Gestión del Aprendizaje',
    'login.emailPlaceholder': 'Ingrese su correo',
    'login.emailAriaLabel': 'Campo de correo',
    'login.passwordPlaceholder': 'Ingrese su contraseña',
    'login.passwordAriaLabel': 'Campo de contraseña',
    'login.showPassword': 'Mostrar contraseña',
    'login.hidePassword': 'Ocultar contraseña',
    'login.rememberAriaLabel': 'Recordarme',
    'login.enter': 'Iniciar Sesión',
    'login.loginAriaLabel': 'Iniciar sesión',
    'login.secureConnection': 'Conexión segura y encriptada',
    'login.loginError': 'Error al iniciar sesión',
    'login.unexpectedError': 'Error inesperado',
    'login.confirmEmail': 'Por favor, confirme su correo',
    'login.rememberMe': 'Recordarme',
    'login.forgotPassword': 'Olvidé mi contraseña',
    'login.viewCourses': 'Ver Cursos Disponibles',
    'login.contactPrompt': '¿Interesado en algún curso?',
    'login.contactButton': 'Contáctanos',
    'login.tooManyAttempts': 'Demasiados intentos de inicio de sesión. Por favor, espere unos minutos.',
    'login.blockedRequest': 'Solicitud bloqueada por seguridad. Intente nuevamente.',

    // Forgot Password
    'forgotPassword.title': 'Recuperar Contraseña',
    'forgotPassword.subtitle': 'Ingrese su correo para recibir instrucciones',
    'forgotPassword.instructions': 'Ingrese su correo registrado y le enviaremos instrucciones para restablecer su contraseña.',
    'forgotPassword.email': 'Correo Electrónico',
    'forgotPassword.emailPlaceholder': 'Ingrese su correo',
    'forgotPassword.send': 'Enviar Instrucciones',
    'forgotPassword.cancel': 'Cancelar',
    'forgotPassword.close': 'Cerrar',
    'forgotPassword.emailRequired': 'El correo es obligatorio',
    'forgotPassword.emailInvalid': 'Correo inválido',
    'forgotPassword.emailNotFound': 'Este correo no está registrado en el sistema',
    'forgotPassword.sendError': 'Error al enviar correo. Intente nuevamente.',
    'forgotPassword.unexpectedError': 'Error inesperado. Intente nuevamente.',
    'forgotPassword.successTitle': '¡Correo Enviado!',
    'forgotPassword.successMessage': 'Revise su bandeja de entrada y siga las instrucciones para restablecer su contraseña.',
    
    // Reset Password
    'resetPassword.title': 'Restablecer Contraseña',
    'resetPassword.subtitle': 'Ingrese su nueva contraseña',
    'resetPassword.expiredTitle': 'Enlace Expirado',
    'resetPassword.expiredSubtitle': 'El enlace de recuperación ya no es válido',
    'resetPassword.newPassword': 'Nueva Contraseña',
    'resetPassword.confirmPassword': 'Confirmar Nueva Contraseña',
    'resetPassword.passwordPlaceholder': 'Ingrese su nueva contraseña',
    'resetPassword.confirmPasswordPlaceholder': 'Confirme su nueva contraseña',
    'resetPassword.passwordRequirement': 'Mínimo 6 caracteres',
    'resetPassword.updatePassword': 'Actualizar Contraseña',
    'resetPassword.backToLogin': 'Volver al Login',
    'resetPassword.passwordRequired': 'La nueva contraseña es obligatoria',
    'resetPassword.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'resetPassword.passwordMismatch': 'Las contraseñas no coinciden',
    'resetPassword.linkExpired': 'El enlace de recuperación ha expirado',
    'resetPassword.linkInvalid': 'Enlace de recuperación inválido',
    'resetPassword.sessionExpired': 'Sesión expirada. Solicite un nuevo enlace de recuperación.',
    'resetPassword.sessionError': 'Error en la sesión de recuperación. Solicite un nuevo enlace.',
    'resetPassword.updateError': 'Error al actualizar contraseña. Intente nuevamente.',
    'resetPassword.unexpectedError': 'Error inesperado. Intente nuevamente.',
    'resetPassword.successTitle': '¡Contraseña Actualizada!',
    'resetPassword.successMessage': 'Su contraseña ha sido cambiada exitosamente. Será redirigido al login.',
    'resetPassword.linkExpiredTitle': 'Enlace Expirado',
    'resetPassword.linkExpiredMessage': 'El enlace de recuperación de contraseña ha expirado. Por favor, solicite un nuevo enlace.',
    'resetPassword.requestNewLink': 'Solicitar Nuevo Enlace',
    
    // Contact form
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Póngase en contacto sobre cursos y oportunidades',
    'contact.name': 'Nombre',
    'contact.namePlaceholder': 'Ingrese su nombre completo',
    'contact.email': 'Correo Electrónico',
    'contact.emailPlaceholder': 'Ingrese su correo',
    'contact.courseInterest': 'Interés en Curso',
    'contact.courseInterestPlaceholder': '¿Qué curso le interesa? (opcional)',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Ingrese su mensaje o pregunta...',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.success': '¡Su cliente de correo se abrió con el mensaje listo. Complete el envío en su correo!',
    'contact.error': 'Error al enviar mensaje. Intente nuevamente.',
    'contact.cancel': 'Cancelar',
    'contact.close': 'Cerrar',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt-BR')

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    // Save language preference
    localStorage.setItem('language', language)
  }, [language])

  const t = (key: string): string => {
    // First check base translations, then extended translations
    const baseTranslations = translations[language] as Record<string, string>
    const extTranslations = extendedTranslations[language] as Record<string, string> | undefined
    const fallbackBase = translations['pt-BR'] as Record<string, string>
    const fallbackExt = extendedTranslations['pt-BR'] as Record<string, string> | undefined
    
    return baseTranslations[key] || 
           extTranslations?.[key] || 
           fallbackBase[key] || 
           fallbackExt?.[key] || 
           key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export function useTranslation() {
  const { t, language, setLanguage } = useLanguage()
  return { t, language, setLanguage }
}
